version: "3"

services:
  ciclo-mongodb:
    image: mongo:3.4
    volumes:
      - ciclo-mongodb-data:/data/db

  ciclo-api:
    depends_on: 
      - ciclo-mongodb
    image: node:8.11
    ports:
      - "80:3000"
    environment:
      - AUTH_SECRET=ultraSecretSalting
      - MONGODB_URI=mongodb://ciclo-mongodb/ciclosPagamentos
      - PORT=3000
    volumes:
      - .:/api
    working_dir: /api
    command: bash -c "npm i && npm run production"

volumes: 
  ciclo-mongodb-data: