version: "3"

services:

  ciclo-mongodb:
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - ciclo-mongodb-data:/data/db

  ciclo-api:
    depends_on: 
      - ciclo-mongodb
    build: .
    command: node_modules/.bin/nodemon --exec npm start
    environment:
      - NODE_ENV=development
      - AUTH_SECRET=ultraSecretSalting
      - MONGODB_URI=mongodb://ciclo-mongodb/ciclosPagamentos
      - PORT=3000
    volumes:
      - .:/home/app/ciclo-pagamento-api
      - /home/app/ciclo-pagamento-api/node_modules # compartilha o node_modules da imagem
    ports:
      - "80:3000"

volumes: 
  ciclo-mongodb-data: